# Generated by Django 5.1.7 on 2025-05-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_propertyfeature_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("off-market", "Off Market"),
                ],
                db_index=True,
                default="available",
                max_length=20,
            ),
        ),
    ]
