# Generated by Django 5.1.7 on 2025-05-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_property_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("cell_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "position",
                    models.CharField(
                        choices=[("agency_admin", "Agency Admin"), ("agent", "Agent")],
                        max_length=20,
                    ),
                ),
                (
                    "permissions",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("view_only", "View Only"),
                        ],
                        default="view_only",
                        max_length=20,
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(
                        default="House of Stone Properties", max_length=200
                    ),
                ),
                ("branch", models.CharField(default="Borrowdale", max_length=100)),
                (
                    "address",
                    models.TextField(default="21 Harare Drive Borrowdale, Harare"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["first_name", "surname"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="area_measurement",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total area of the property",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="area_unit",
            field=models.CharField(
                choices=[
                    ("sqm", "Square Meters"),
                    ("sqft", "Square Feet"),
                    ("hectares", "Hectares"),
                    ("acres", "Acres"),
                ],
                default="sqm",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[("rental", "Rental"), ("sale", "Sale")],
                default="sale",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PropertyAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary agent responsible for this property",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_properties",
                        to="core.agent",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_agents",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Agent",
                "verbose_name_plural": "Property Agents",
                "unique_together": {("property", "agent")},
            },
        ),
    ]
