# Generated by Django 5.1.7 on 2025-05-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_agent_property_area_measurement_property_area_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="lot_size",
            new_name="floor_size",
        ),
        migrations.AddField(
            model_name="property",
            name="dining_rooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="kitchens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="lounges",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
