# Generated by Django 5.1.7 on 2025-10-14 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_property_agent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="agent",
            new_name="user",
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["is_published", "status", "property_type"],
                name="core_proper_is_publ_8770e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["category", "status", "created_at"],
                name="core_proper_categor_fee45b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["user", "is_published", "status"],
                name="core_proper_user_id_2a7662_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["price", "property_type"], name="core_proper_price_473a68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["location", "category"], name="core_proper_locatio_760b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["created_at"], name="core_proper_created_a942a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price"], name="core_proper_price_652b7d_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["beds"], name="core_proper_beds_d7266c_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["baths"], name="core_proper_baths_0a36fd_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["location"], name="core_proper_locatio_8c20f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "category", "status"],
                name="core_proper_propert_e02bcb_idx",
            ),
        ),
    ]
