# Generated by Django 5.1.7 on 2025-11-09 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_agent_property_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyimage",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
