# Generated by Django 5.1.7 on 2025-11-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_property_property_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[
                    ("rental", "Rental"),
                    ("sale", "Sale"),
                    ("development", "Development"),
                ],
                default="sale",
                max_length=20,
            ),
        ),
    ]
