# Generated by Django 5.1.7 on 2025-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_property_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("land", "Land"),
                    ("commercial", "Commercial"),
                    ("villa", "Villa"),
                ],
                max_length=20,
            ),
        ),
    ]
