# Generated by Django 5.1.7 on 2025-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="optimized_image",
            field=models.ImageField(blank=True, null=True, upload_to="optimized/"),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="watermarked_image",
            field=models.ImageField(blank=True, null=True, upload_to="watermarked/"),
        ),
    ]
