# Generated by Django 5.1.7 on 2025-11-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_propertyimage_optimized_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyimage",
            name="optimized_image",
        ),
        migrations.RemoveField(
            model_name="propertyimage",
            name="processing_status",
        ),
        migrations.RemoveField(
            model_name="propertyimage",
            name="watermarked_image",
        ),
    ]
