# Generated by Django 5.1.7 on 2025-11-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_propertyimage_optimized_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="is_watermarked",
            field=models.BooleanField(default=False),
        ),
    ]
