# Generated by Django 5.1.7 on 2025-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_propertyimage_is_watermarked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("land", "Land"),
                    ("commercial", "Commercial"),
                    ("villa", "Villa"),
                    ("cluster", "Cluster"),
                    ("stand", "Stand"),
                    ("duplex", "Duplex"),
                ],
                max_length=20,
            ),
        ),
    ]
