# Generated by Django 5.1.7 on 2025-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_property_property_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[
                    ("rental", "Rental"),
                    ("sale", "Sale"),
                    ("development", "Development"),
                    ("commercial", "Commercial Property"),
                    ("industrial", "Industrial Property"),
                ],
                default="sale",
                max_length=20,
            ),
        ),
    ]
