# Generated by Django 5.1.7 on 2026-01-16 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_inquiry_options_inquiry_email_inquiry_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('property_created', 'Property Created'), ('property_updated', 'Property Updated'), ('property_deleted', 'Property Deleted'), ('property_status', 'Property Status Changed'), ('agent_created', 'Agent Created'), ('agent_updated', 'Agent Updated'), ('agent_deleted', 'Agent Deleted'), ('user_created', 'User Registered'), ('user_updated', 'User Updated'), ('inquiry_received', 'Inquiry Received'), ('property_shared', 'Property Shared'), ('lead', 'New Lead'), ('alert', 'System Alert'), ('info', 'Information')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Target user for this notification. Null means for all admins.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='core_notifi_user_id_cb8d84_idx'), models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx')],
            },
        ),
    ]
