# Generated by Django 5.1.7 on 2026-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('flat', 'Flat'), ('land', 'Land'), ('commercial', 'Commercial'), ('villa', 'Villa'), ('cluster', 'Cluster'), ('stand', 'Stand'), ('duplex', 'Duplex'), ('townhouse', 'Townhouse')], max_length=20),
        ),
    ]
