# Generated by Django 5.1.7 on 2026-01-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
    ]
